spring:
  datasource:
    url: jdbc:mysql://localhost:3306/seckill?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
    username: root
    password: root
  mvc:
      view:
        prefix: /WEB-INF/jsp/
        suffix: .jsp